name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GithubBotToken: ${{ secrets.GITHUBBOT_TOKEN }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/Wally
    - name: Build
      run: dotnet build src/Wally --no-restore
    - name: Run
      run: dotnet run --project src\Wally\Wally.csproj
